name: Generate GitHub Stats

on:
  schedule:
    # Runs every 24 hours
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update README with GitHub Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Generate GitHub Stats
        run: node index.js
      - name: Commit and push changes
        run: |
          git config --global user.email "murichustephen@gmail.com"
          git config --global user.name "munuhee"
          git add .
          git commit -m "Update GitHub Stats"
          git push
